# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3950226be4776e8f9fd21b324468ef796c432ddee9f43d3b2681f1861ab011e9fae6284ce1e086932d15474107b39ad725ebaf0c8c8dd0a2ee1b6ff68ecffe59

test:
  secret_key_base: 23ab2accee1cbf9e066f57dcf337de573b60e65c0e1bb2a0ac72fc0bd9f864894b4119bb29c6505440a81ff8ffe4e63fdf44abfc84d9cb19be58eb1c44c474b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
